import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Attivanse | Diseño web para Empresas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* el nav tiene mb-[-161] para estar sobre el header*/}
        <div className='z-10 relative mb-[-161px] pt-[64px] flex pl-28 pr-40 justify-between'>
          <Image className='h-[46px] w-[240px]' width={240} height={46} alt='logo-attivanse' src="/img/attivanse-logo.png" />
          <ul className='flex gap-10'>
            <li><a href="">Servicios</a></li>
            <li><a href="">Metodología</a></li>
            <li><a href="">Precios</a></li>
            <li><a href="">Contacto</a></li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  )
}
